<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <title>Document</title>
</head>
<body>

<h3>Title1</h3>

<ul>
    <li class="static">text1</li>
    <li class="static">text2</li>
    <li class="static">text3</li>
    <li class="static">text4</li>
    <li class="static">text5</li>
    <li class="static">text6</li>
    <li class="static"text7</li>
    <li class="static">text8</li>
    <li class="static">text9</li>
    <li class="static">text10</li>
    <li class="static">text11</li>
</ul>

<h3>Title2</h3>
<h2>Title3</h2>

<p id="first" onclick="viewParOne()">Click if you want show paragraph 1</p>
<p class="paragraph" id="par1">1 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p id="second" onclick="viewParTwo()">Click if you want show paragraph 2</p>
<p class="paragraph" id="par2">2 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p id="third" onclick="viewParThree()">Click if you want show paragraph 3</p>
<p class="paragraph" id="par3">3 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<input type="text" name="input1" id="inp1">
<input type="text" name="input2" id="inp2">
<input type="text" name="input3" id="inp3">

<p id="num1">2</p>
<p id="num2">4</p>

<ul id="dinamic">
    <li>Пункт</li>
    <li>Пункт</li>
</ul>
<input type="button" id="add" value="Добавить пункт">
<script>
    //1) Всем <h3> поставьте текст '!!!'.
    $('h3').html('!!!');

    //2) Всем <h3> сделайте жирный текст зеленого цвета.
    $('h3').css('color', 'green');
    $('h3').css('font-weight', 'bold');

    //3) Поменяйте всем <li> на странице их текст на их порядковый номер.
    $('li.static').each(function (index, elem) {
        $(this).html(index);
    });

    /*4) Получите и покрасьте в красный цвет следующие элементы:
    - первую <li> на странице
    - последнюю <li> на странице.
    - Четные <li>*/
    $('li:first').css('color', 'red');
    $('li:last').css('color', 'red');
    $('li:odd').css('color', 'red');

    //5) Перед каждым <h2> вставьте '<p>!</p>'.
    $('h2').before('<p>!</p>');

    //6) Добавьте всем li класс test
    $('li').addClass('test');

    //События:
    //1) Даны абзацы. Сделайте так, чтобы по клику на каждый абзац на экран выводилось его содержимое.
    $('.paragraph').css('display', 'none');
    function viewParOne(){
        document.getElementById("par1").style.display = "block";
    };function viewParTwo(){
        document.getElementById("par2").style.display = "block";
    };function viewParThree(){
        document.getElementById("par3").style.display = "block";
    };

    //2) Привяжите всем инпутам событие - по потери фокуса каждый инпут выводит свое value в консоль
    $('input').focusout(function () {
        console.log($('input').val())
    });

    //3) Даны абзацы с числами. По нажатию на абзац в нем должен появится квадрат числа, которое он содержит.
    $('#num1').click(function () {
        $('#num1').html(Math.pow(parseInt($('#num1').text(),10),2))
        });
    $('#num2').click(function () {
        $('#num2').html(Math.pow(parseInt($('#num2').text(),10),2))
        });

    //4)  Дан ul, в нем несколько li. Под ul сделайте кнопку, по нажатию на которую в конец ul будет добавляться новый li с текстом 'пункт'
    $('#add').click(function () {
        $('#dinamic').append('<li>пункт</li>');
    });
</script>
</body>
</html>